cd preprocessed

mkdir section2
cd section2

mkdir outs
cd outs

wget https://cf.10xgenomics.com/samples/spatial-exp/1.1.0/V1_Mouse_Brain_Sagittal_Posterior_Section_2/V1_Mouse_Brain_Sagittal_Posterior_Section_2_raw_feature_bc_matrix.tar.gz
wget https://cf.10xgenomics.com/samples/spatial-exp/1.1.0/V1_Mouse_Brain_Sagittal_Posterior_Section_2/V1_Mouse_Brain_Sagittal_Posterior_Section_2_spatial.tar.gz

gunzip V1_Mouse_Brain_Sagittal_Posterior_Section_2_raw_feature_bc_matrix.tar.gz
tar -xvf V1_Mouse_Brain_Sagittal_Posterior_Section_2_raw_feature_bc_matrix.tar

gunzip V1_Mouse_Brain_Sagittal_Posterior_Section_2_spatial.tar.gz 
tar -xvf V1_Mouse_Brain_Sagittal_Posterior_Section_2_spatial.tar

# clean up
rm V1_Mouse_Brain_Sagittal_Posterior_Section_2_raw_feature_bc_matrix.tar
rm V1_Mouse_Brain_Sagittal_Posterior_Section_2_spatial.tar